# Generated by Django 4.0.3 on 2022-03-20 22:02

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=app.models.project_file_upload)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
    ]
