# Generated by Django 4.0.3 on 2022-03-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fileExt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
